name: Repository Reporting

on:
  workflow_call:
    secrets:
      token:
        description: 'Secret token from caller workflow to access private repos'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List Org Repos
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.token }}
          script: |
            const orgName = 'teamkfinteg'
            const responses = await github.repos.listForOrg({ org: orgName })
            const responseData = responses.data
            console.log("Total repositories: " + responseData.length)
            for (const response of responseData) {
              const rURL = response.html_url
              const rName = response.name
              const lTeams = await github.repos.orgName.rName.teams
              console.log(rURL)
              console.log(rName)
              console.log(lTeams)
            }




 