name: Repository Reporting

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check using github-script 1
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const rname = context.payload.repository.name
            console.log(`${ rname }`)
      - name: Check using github-script 2
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const responses = await github.repos.listForOrg({ org: 'keyfactor' })
            const responseData = responses.data
            for (const response of responseData) {
              console.log(response.html_url)
              console.log(response.full_name)
            }




 